### ISSUE TITLE
TPC-C Load fails via proxy

### ISSUE THREAD

**Issue by andygrove** [AgilData/mysql-proxy-rs#14]
The load works with mysql-router but will not work with mysql-proxy-rs and here is the error from our TPCC:

```
java.lang.RuntimeException: Error loading into table 'item' with SQL: INSERT IGNORE INTO `item` (i_id,i_im_id,i_name,i_price,i_data) VALUES (1,2816,'A6orZi0q5MGNmqNcMO',76.14,'k5LFMuM05JbY3ztNZa4Y5r8L0rU0VrpwVQpMPlP0g76MEVBspS'),(2,896,'Q78ZjbjJa3DJuUgWhZw',36.62,'aXQNsiRyGQZHJlNjgpLlWm2CpoSJR'),(3,9431,'7JZrAOnIHSVoYPwp1sLi',77.29,'Qo3aiqTrLLYutXg7NXb8YBo9cKSPyHHoOrJjWIcpsCjCRAIzmP')….( a lot more inserts here)
    at com.codefutures.tpcc.load.JdbcStatementLoader.executeBulkInsert(JdbcStatementLoader.java:72)
    at com.codefutures.tpcc.load.JdbcStatementLoader.load(JdbcStatementLoader.java:59)
    at com.codefutures.tpcc.Load.loadItems(Load.java:83)
    at com.codefutures.tpcc.TpccLoad.runLoad(TpccLoad.java:263)
    at com.codefutures.tpcc.TpccLoad.main(TpccLoad.java:334)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 4 milliseconds ago.  The last packet sent successfully to the server was 2 milliseconds ago.
```

all the proxy says is this: 

```
Failed to spawn future: Error { repr: Custom(Custom { kind: Other, error: StringError("connection closed") }) }
```

**Comment by andygrove** [comment]
I'm guessing this may have something to do with the current hard-coded 4K buffers or not ensuring capacity before reading into buffers

**Comment by ajmanlove** [comment]
https://github.com/AgilData/mysql-proxy-rs/pull/15

**Comment by ajmanlove** [comment]
Improved: https://github.com/AgilData/mysql-proxy-rs/pull/16
